// Define your acronyms here
// For more information look at the used package https://typst.app/universe/package/acrostiche

#let acronyms = (
  "AI": ("Artificial Intelligence"),
  "BFS": ("Breadth-First Search"),
  "CNN": ("Convolutional Neural Network"),
  "CUDA": ("Compute Unified Device Architecture"),
  "D4RL": ("Datasets for Deep Data-Driven Reinforcement Learning"),
  "DQN": ("Deep Q-Network"),
  "EMA": ("Exponential Moving Average"),
  "GAE": ("Generalized Advantage Estimation"),
  "GPT": ("Generative Pre-trained Transformer"),
  "gRPC": ("Google Remote Procedure Call"),
  "GTrXL": ("Gated Transformer-XL"),
  "IT": ("Informationstechnologie"),
  "KI": ("Künstliche Intelligenz"),
  "LSTM": ("Long Short-Term Memory"),
  "MDP": ("Markov Decision Process"),
  "ML": ("Machine Learning"),
  "MLP": ("Multi-Layer Perceptron"),
  "ONNX": ("Open Neural Network Exchange"),
  "PBRS": ("Potential-Based Reward Shaping"),
  "PPO": ("Proximal Policy Optimization"),
  "RL": ("Reinforcement Learning"),
  "RNN": ("Recurrent Neural Network"),
  "SAC": ("Soft Actor-Critic"),
  "TD": ("Temporal Difference"),
  "YAML": ("YAML Ain't Markup Language"),
)